version: "3.9"
services:
  jupyter-server:
    build: .
    ports:
      - "10000:8888"
  postgres-server:
    image: "postgres:13"
    environment:
      POSTGRES_USER: dej
      POSTGRES_PASSWORD: dej
      POSTGRES_DB: dej

  pgadmin-server:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: dej@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dej
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
